### PR TITLE
Az162 general cleanup and improvement

### PR DESCRIPTION
**Pull request by ian-plosker**
First steps in moving riaknostic forward. Simplified code. Moved side effects into the `riaknostic:run` function. Got rid of multiple dicts.
## TODO
- Rethink the individual diagnostic modules
- More diagnostics
- Read vm.args?

### CODE REVIEW

**Comment by ian-plosker** [comment]
There is a lot more work that needs to be done here. This pull request is premature.

**Comment by ian-plosker** [comment]
Looking better. Ready for comments.

**Comment by ian-plosker** [comment]
Should a squash all these commits into one before pushing?

**Comment by ian-plosker** [comment]
Finished all of Mathias's proposed diagnostics. Any more recommendations?

**Comment by seancribbs** [comment]
- `riaknostic.erl`
  - When searching in `fetch_stats` for the `sys_otp_version`, use `lists:keyfind/3` instead of `lists:foreach/2` (you don't need to iterate through the whole list).
  - Instead of specifying all the modules to run as strings in a list in the .app file, I would instead use `application:get_key(riaknostic, modules)` to get the module list, then filter them by `Mod:module_info(exports)`, looking for `{run,1}` in the exports list.
  - Start riaknostic as a hidden node, which will prevent cluster nodes from trying to connect to it or printing errors when it disconnects. Look at the nodetool in the riak repo for how to do this.
- `riaknostic_opts.erl`
  - Consider putting the CLI options parsing in the modules where it is used, or make a generic options parser and apply the configuration when needed.

**Pull request merged**
