### PR TITLE
Documentation updates

### PR DESCRIPTION
**Pull request by brianshumate**
Thanks for the great work on this tool! Here are some docs updates for issues #26 and #29.

### CODE REVIEW

**Comment by ghost** [comment]
One of the strategies we've been trying to do is create a feature/bug-fix branch on basho/riaknostic itself, and merge from there. So bs-doc-update would be a good feature branch on basho/riaknostic.

Another thing that I want use to start doing is referencing the issues we're addressing in the commit messages, such as "fixes #xxx". 

I'll look over the actual commits in just a second, but I'll also try and do a presentation on how to use git/GitHub for everyone, since I haven't described it before. ^^

**Comment by brianshumate** [comment]
Understood.

I can definitely commit to a feature branch instead of master from now on. My understanding might be wrong, but I thought addressing issues by number in the way you've described will actually immediately close that issue, and I did not want to have that happen on a PR that no one had even read yet. :)

That said, a presentation like "getting along on Github" would be welcome, because I've never used it daily in a collaborative way, and so my fu is certainly weak.

**Comment by Vagabond** [comment]
Yes, putting 'Fixes #X' will close issue #X.

**Comment by ghost** [comment]
The migration to DEVELOPMENT.md looks good to me. +1

**Pull request merged**
