### PR TITLE
Check to confirm all preflists satisfy n_val

### PR DESCRIPTION
**Pull request by ian-plosker**
Uses `riak_core_ring_util:check_ring/0`

### CODE REVIEW

**Comment by seancribbs** [comment]
+1

**Comment by tovbinm** [comment]
What's the purpose of this check?

**Comment by seancribbs** [comment]
@tovbinm The name and messaging is probably a little misleading. When you have a cluster that is too small, you do not have a guarantee that all replicas will be on different nodes. This check will warn you of that situation.

**Comment by tovbinm** [comment]
Thanks, Sean. 
How do I decrease the n_val for preflists?!

**Comment by seancribbs** [comment]
You would decrease the `n_val` property on the bucket, fundamentally, decreasing the number of replicas.

**Comment by tovbinm** [comment]
Yeah, but diag does not output any bucket information:

#riak-admin diag
11:37:11.812 [warning] The following preflists do not satisfy the n_val: [[{22835963083295358096932575511191922182123945984,'riak@r001'},..]...]

How do I know to which bucket it's related?

**Pull request merged**
